### ISSUE TITLE
Make error with 'gemm.cpp'

### ISSUE THREAD

**Issue by shana34** [ROCmSoftwarePlatform/rocBLAS-Examples#29]
![微信图片_20200812170336](https://user-images.githubusercontent.com/22281195/89996785-d218ed00-dcbd-11ea-88a4-e9b6da69af11.png)

**Comment by TorreZuk** [comment]
Thanks for the feedback.  That symbol should be the last few releases of rocBLAS so would like to know what version of ROCm or rocBLAS you are building against?   If you download and build a local newer version of rocBLAS which isn't installed you can use it by setting the environment variable: 
export ROCBLAS_PATH=/...yourlocalpath.../rocBLAS/build/release/rocblas-install
I'll update the documentation to specify a minimum ROCm  (3.5+).

**Comment by shana34** [comment]
My rocm is v2.9, so this question is raised by the version of Rocm?

**Comment by shana34** [comment]
and rocblas is v2.6

**Comment by TorreZuk** [comment]
Documentation was updated so closing this old task.  The latest master will require rocm and rocblas 4.2 or later for some examples.
